### ISSUE TITLE
CF deploy fails with following error

### ISSUE THREAD

**Issue by mossuchida** [RuntimeTools/appmetrics-dash#123] opened 2017-11-09 15:39 UTC
I followed the following link, but failing with the error below:
https://developer.ibm.com/node/2017/03/23/use-appmetrics-dash-bluemix-3-easy-steps/

2017-11-09T10:31:52.90-0500 [APP/PROC/WEB/0] ERR [Thu Nov  9 15:31:52 2017] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 3.1.3.201711070422 (Agent Core 3.2.6)
2017-11-09T10:31:52.97-0500 [APP/PROC/WEB/0] ERR [Thu Nov  9 15:31:52 2017] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/mongodb/lib/mongo_client.js:369
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR             throw err
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR             ^
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR RangeError: Maximum call stack size exceeded
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Object.stringify (native)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Function.Module._findPath (module.js:158:25)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (module.js:467:25)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:417:25)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Module.require (module.js:497:17)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Module.newFunc (/home/vcap/app/node_modules/appmetrics/lib/aspect.js:101:26)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at require (internal/module.js:20:19)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Object.exports.monitor (/home/vcap/app/node_modules/appmetrics-dash/lib/appmetrics-dash.js:99:42)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Object.exports.monitor (/home/vcap/app/node_modules/appmetrics-dash/lib/appmetrics-dash.js:103:31)
2017-11-09T10:31:53.73-0500 [APP/PROC/WEB/0] ERR     at Object.http.Server (/home/vcap/app/node_modules/appmetrics-dash/lib/appmetrics-dash.js:69:15)
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-75-generic
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! node v6.11.4
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! npm  v3.10.10
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! acmeair_flight@0.1.0 start: `node flightservice_app.js`
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! 
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Failed at the acmeair_flight@0.1.0 start script 'node flightservice_app.js'.
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! If you do, this is most likely a problem with the acmeair_flight package,
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR!     node flightservice_app.js
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs acmeair_flight
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls acmeair_flight
2017-11-09T10:31:53.75-0500 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
2017-11-09T10:31:53.76-0500 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
2017-11-09T10:31:53.76-0500 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log

**Comment by mattcolegate** [comment] 2017-11-09 16:58
This could be a duplicate of RuntimeTools/appmetrics#489, it's unlikely that appmetrics-dash will work if the underlying appmetrics is not working.

**Comment by mossuchida** [comment] 2017-11-09 17:27
Hi, Toby, I was using this to just test out the appmetrics-dash : https://github.ibm.com/ibmperf/flightservice-node

**Comment by mattcolegate** [comment] 2017-11-09 17:56
Closing as issue was fixed in RuntimeTools/appmetrics#489

**Closed by mattcolegate** 2017-11-09 17:56 UTC
