### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jinnyum** [RuntimeTools/appmetrics-dash#172] opened 2019-04-10 01:17 UTC
I get an error when installing.
Can you tell me how to fix it?

![error](https://user-images.githubusercontent.com/38673939/55844710-9f1a9280-5b79-11e9-8d7e-b7d39655c073.png)

**Comment by peterpanBest** [comment] 2020-02-13 13:56
> I get an error when installing.
> Can you tell me how to fix it?
> 
> ![error](https://user-images.githubusercontent.com/38673939/55844710-9f1a9280-5b79-11e9-8d7e-b7d39655c073.png)

what's ur Nodejs version ? Maybe this library is not working in old Nodejs version .

**Comment by nmargaritis** [comment] 2020-04-16 10:40
This module works only with node v10. in current LTS v12 the module can not be installed due to node-gyp issues.

Note that v10 has a support up until April 2021. So currently the clock is ticking and I really do not know if you guys will consider using v10 instead of v12 for a performance evaluation module.... You already compromise performance by staying in v10.

**Comment by mattcolegate** [comment] 2020-04-28 23:55
Hi @nmargaritis, thanks for your comment - it's prompted me to update our automated testing for appmetrics-dash. You can see the PR I've raised for it (#188) and hopefully you can see the resulting Travis run (https://travis-ci.org/github/RuntimeTools/appmetrics-dash/builds/680791283) that shows that on Linux and OSX appmetrics-dash works on all currently supported versions of Node.js (v10, v12, v13 and v14). For the Windows errors, we see the same kind of test errors on appmetrics which is likely the cause - I've opened RuntimeTools/appmetrics#637 to fix those up - but in all cases, appmetrics-dash does install. In light of all appmetrics-dash installations with supported Node.js versions installing correctly (albeit with warnings) at this time, I'm going to close this issue.

**Closed by mattcolegate** 2020-04-28 23:55 UTC

**Comment by alexshenker** [comment] 2024-01-11 17:45
> This module works only with node v10. **in current LTS v12 the module can not be installed due to node-gyp issues.**
> 
> Note that v10 has a support up until April 2021. So currently the clock is ticking and I really do not know if you guys will consider using v10 instead of v12 for a performance evaluation module.... You already compromise performance by staying in v10.
> 
> [Benchmarking node v12, v10, v8, v6, v4](https://medium.com/@ersun.warncke/benchmarking-node-js-v12-vs-v10-v8-v6-v4-and-go-89d28eee603d)

Have you managed to resolve this issue? I'm also **only** able to install appmeetrics-dash with nodeJS 10, no later.
