### ISSUE TITLE
cpu/memory/enviornment does not show up on mac OS

### ISSUE THREAD

**Issue by smartmouse** [RuntimeTools/appmetrics-dash#33] opened 2017-03-03 20:22 UTC
The charts for cpu/memory/environment does not show informatio on MacOSX. These are working on linux and windows.

Just use any simple loopback app on mac OSX

<img width="1213" alt="screen shot 2017-03-03 at 2 58 42 pm" src="https://cloud.githubusercontent.com/assets/4519627/23567512/90d1bc1a-0024-11e7-9317-7ba62373ca4b.png">

on windows it is okay
on linux it is okay

<img width="1276" alt="screen shot 2017-03-03 at 3 21 58 pm" src="https://cloud.githubusercontent.com/assets/4519627/23567628/3296a632-0025-11e7-88a4-86e4e69e300c.png">

**Comment by smartmouse** [comment] 2017-03-03 20:22
@sam-github ^^

**Comment by sam-github** [comment] 2017-03-03 21:16
@tobespc, does appmetrics support OS X?

**Comment by tobespc** [comment] 2017-03-06 09:44
should be working fine, I'll test it out on my mac today

**Comment by tobespc** [comment] 2017-03-06 11:00
can you paste you testcase please.  Its working fine for us

![image](https://cloud.githubusercontent.com/assets/13151286/23607274/24619f34-025c-11e7-84d1-89088396e98d.png)

**Comment by sjanuary** [comment] 2017-03-06 11:30
@smartmouse - looks like you were only running for about 10 seconds on Mac, could you also try a longer run please?

**Comment by smartmouse** [comment] 2017-03-06 18:11
what macOSX are you using?  I am using macOSX sierra.
At least you should show the environment etc.

<img width="1203" alt="screen shot 2017-03-06 at 1 08 14 pm" src="https://cloud.githubusercontent.com/assets/4519627/23622802/0f3ed25e-026e-11e7-8674-4b3a5a31c2a7.png">

<img width="634" alt="screen shot 2017-03-06 at 1 03 58 pm" src="https://cloud.githubusercontent.com/assets/4519627/23622848/38718b80-026e-11e7-8e2c-d37303f48fd8.png">


To reproduce 
apic loopback  ( create a lb3 - notes sample)
apic start

**Comment by sam-github** [comment] 2017-03-06 19:00
Since code is unreleased ATM, reproduction using `apic` is impossible outside of the APIC team.

@smartmouse can you give `npm ls -g apic | grep appmetrics` output, please, so versions you are using are known?

@tobespc were you using different mac versions from Ivy?

**Comment by smartmouse** [comment] 2017-03-06 22:15
Is appmetrics a direct dependency for apiconnect? , does not seem to see it under apiconnect 's package.json

on mac 
reserved-192-168-1-3:~ smartmouse$ npm ls -g apic | grep appmetrics
npm ERR! code 1

BUT 
I checked the versions of the appmetrics installed under apiconnect\node_modules\

```
reserved-192-168-1-3:appmetrics-dash smartmouse$ tail package.json
  "repository": {
    "type": "git",
    "url": "git+https://github.com/RuntimeTools/appmetrics-dash.git"
  },
  "scripts": {
    "pretest": "eslint .",
    "test": "tap test/test-*.js"
  },
  "version": "3.0.0-RC.1"
}
reserved-192-168-1-3:appmetrics-dash smartmouse$ pwd
/Users/smartmouse/.nvm/versions/node/v6.9.5/lib/node_modules/apiconnect/node_modules/appmetrics-dash
reserved-192-168-1-3:appmetrics-dash smartmouse$ cd ../appmetrics
reserved-192-168-1-3:appmetrics smartmouse$ tail package.json 
  "repository": {
    "type": "git",
    "url": "git://github.com/RuntimeTools/appmetrics.git"
  },
  "scripts": {
    "install": "node extract_all_binaries.js",
    "test": "tap --reporter tap --timeout=120 tests/api_tests.js tests/headless_test.js"
  },
  "version": "1.2.0"
}
reserved-192-168-1-3:appmetrics smartmouse$ pwd
/Users/smartmouse/.nvm/versions/node/v6.9.5/lib/node_modules/apiconnect/node_modules/appmetrics
reserved-192-168-1-3:appmetrics smartmouse$ 

```


on the linux machine where the appmetrics-dash is showing, stilll shows nothing

```
root@csx00392:~# which apic
/root/node480/bin/apic
root@csx00392:~# node -v
v4.8.0
root@csx00392:~# npm -v
4.3.0
root@csx00392:~# apic -v
API Connect: vdev (apiconnect: v2.5.29)
root@csx00392:~# npm ls -g apic | grep appmetrics
root@csx00392:~# 

```

**Comment by sam-github** [comment] 2017-03-06 23:11
Sorry, I forgot, your package and CLI name differ: `npm ls -g apiconnect | grep appmetrics`

**Comment by smartmouse** [comment] 2017-03-06 23:48
actually I did that already too :-)  but it returns nothing on both mac ad linux

```
root@csx00392:~# apic -v
API Connect: vdev (apiconnect: v2.5.29)
root@csx00392:~# npm ls -g apic | grep appmetrics
root@csx00392:~# npm ls -g apiconnect | grep appmetrics
root@csx00392:~# npm ls -g apiconnect | grep appmetrics-dash
```


```
reserved-192-168-1-3:~ smartmouse$ npm ls -g apiconnect | grep appmetrics
reserved-192-168-1-3:~ smartmouse$ 

```

**Comment by smartmouse** [comment] 2017-03-06 23:54
I wonder if that is due to nvm. On linux or even windows , I do not have nvm installed.
but on Mac I use nvm to manage multiple versions of node.js runtime.

**Comment by sam-github** [comment] 2017-03-07 05:57
I use nvm, works for me. Can you try another mac? Or tell me how exactly to
repro on my mac? Its been a while since I've installed apic from dev
registries.

**Comment by smartmouse** [comment] 2017-03-08 04:18
I can confirm now, It has nothing to do with nvm, I uninstall nvm and use
normal node , the same issue. no cpu/memory/environment.
but other requests and event loop chart shows data., so it must be this
particular type of Mac OSX version I have.

I  may be able to use the mac-mini and try .


You can do npm install -g apiconnect --registry
apiconnect01.rchland.ibm.com:4873.

**Comment by sam-github** [comment] 2017-03-08 17:52
@smartmouse ```
~ % npm install -g apiconnect --registry http://apiconnect01.rchland.ibm.com:4873 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @console/bluemix-icons@^3.3.0 (node_modules/apiconnect/node_modules/apim-ui/node_modules/@console/bluemix-icons):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: no such package available : @console/bluemix-icons
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/sam/.nvm/versions/node/v7.7.1/bin/node" "/Users/sam/.nvm/versions/node/v7.7.1/bin/npm" "install" "-g" "apiconnect" "--registry" "http://apiconnect01.rchland.ibm.com:4873"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 no such package available : @console/bluemix-components
npm ERR! 404 
npm ERR! 404  '@console/bluemix-components' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'apim-ui'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sam/npm-debug.log
```

> ~ % uname -a
> Darwin sambook.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

**Comment by smartmouse** [comment] 2017-03-09 01:05
They are trying to fix the build currently. So retry tmr for a better build and the bundle issue should also be resolved as well.

**Comment by smartmouse** [comment] 2017-03-09 01:07
alternately you can download this bundle
 https://apim-jenkins.hursley.ibm.com/view/All/job/apiconnect-bundles/2294/

it should have the appmetrics supprt already - good thing we start early the code is merged in before everything else goes in and broken all over the place.

**Comment by sam-github** [comment] 2017-03-10 17:16
Cannot reproduce.

```
/tmp/fu % apic start
Service fu started on port 4001. Access the application dashboard at http://127.0.0.1:4001/appmetrics-dash
Service fu-gw started on port 4002.
/tmp/fu % uname -a
Darwin sambook.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
/tmp/fu % apic --version; node --version; npm --version
API Connect: vdev (apiconnect: v2.6.0)
v4.8.0
2.15.11
```

OS X version 10.11.6

Installed from https://apim-jenkins.hursley.ibm.com/view/All/job/apiconnect-bundles/2318/

![cpu-memory-on-osx](https://cloud.githubusercontent.com/assets/17607/23805252/001d5d5c-0572-11e7-9965-1d57d43d41cf.png)

@smartmouse

**Comment by smartmouse** [comment] 2017-03-11 17:59
@sam-github  I think this issue may be specific Mac OS Sierra 10.12 - we can close this if some other macOSX can launch it. but I am using node 6.9.5 and npm. 3.10.10 but same results as Node 4.x

**Comment by tobespc** [comment] 2017-04-24 13:12
@smartmouse I'm running on Mac OS Sierra 10.12 and I get all the data from appemtrics-dash

**Comment by smartmouse** [comment] 2017-04-24 18:06
@tobespc , just to make sure we are comparing apples to apples, how are you running?
You are install the appmetrics yourself as standalone tool? or u are installing it from apiconnect bundle?
Do you need to set up any compilers ? toolchain?


```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by tobespc** [comment] 2017-04-25 07:22
@smartmouse are ok, yes I just installed as Standalone tool and it works ok.  Should this issue be raised on this git repo if its apiconnect bundling problem ?

**Comment by sjanuary** [comment] 2017-05-02 11:19
Closing as it seems to be a packaging issue with another product

**Closed by sjanuary** 2017-05-02 11:19 UTC
Labels: invalid
