### ISSUE TITLE
Does not install on node V.11.1.0 on mac

### ISSUE THREAD

**Issue by suprithwork** [RuntimeTools/appmetrics-dash#168] opened 2018-12-30 13:29 UTC
Currently it gives me a node-gyp build error when I am trying to install with a lot deprecated warnings.

Replacing '"99\.99\.99\.29991231"' with '"3.1.3.201812301423"'
  CXX(target) Release/obj.target/appmetrics/geni/appmetrics.o
In file included from Release/obj.target/appmetrics/geni/appmetrics.cpp:25:
In file included from ../src/plugins/node/prof/watchdog.h:21:
../src/plugins/node/prof/compat-inl.h:302:19: error: no member named 'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StartProfiling(title, record_samples);
         ~~~~~~~  ^
../src/plugins/node/prof/compat-inl.h:312:19: error: no member named 'GetCpuProfiler' in 'v8::Isolate'
  return isolate->GetCpuProfiler()->StopProfiling(title);
         ~~~~~~~  ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:90:8: warning: 'WriteUtf8' is deprecated: Use Isolate* version
      [-Wdeprecated-declarations]
    s->WriteUtf8(buf);
       ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:187:117: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    std::string moduleFilename(toStdString(module->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked())->ToS...
                                                                                                                    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:192:112: warning: 'ToObject' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    return Nan::GetCurrentContext()->Global()->Get(Nan::New<String>(asciiString("process")).ToLocalChecked())->ToObject();
                                                                                                               ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:198:41: warning: 'ToObject' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        return getModuleDir(mainModule->ToObject());
                                        ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:333:34: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
                Local<String> value = info[0]->ToString();
                                               ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:334:37: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
    Local<String> value1 = info[1]->ToString();
                                    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:344:34: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
                Local<String> value = info[0]->ToString();
                                               ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:383:34: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
  Local<String> value = info[0]->ToString();
                                 ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:435:29: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        listener->callback->Call(argc, argv);
                            ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:495:40: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        String::Utf8Value str(info[0]->ToString());
                                       ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:495:27: warning: 'Utf8Value' is deprecated: Use Isolate version
      [-Wdeprecated-declarations]
        String::Utf8Value str(info[0]->ToString());
                          ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:505:40: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        String::Utf8Value str(info[1]->ToString());
                                       ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:505:27: warning: 'Utf8Value' is deprecated: Use Isolate version
      [-Wdeprecated-declarations]
        String::Utf8Value str(info[1]->ToString());
                          ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:531:45: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        String::Utf8Value topicArg(info[0]->ToString());
                                            ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:531:27: warning: 'Utf8Value' is deprecated: Use Isolate version
      [-Wdeprecated-declarations]
        String::Utf8Value topicArg(info[0]->ToString());
                          ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:532:47: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        String::Utf8Value commandArg(info[1]->ToString());
                                              ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:532:27: warning: 'Utf8Value' is deprecated: Use Isolate version
      [-Wdeprecated-declarations]
        String::Utf8Value commandArg(info[1]->ToString());
                          ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:662:41: warning: 'ToObject' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        Local<Value> filename = parent->ToObject()->Get(Nan::New<String>(asciiString("filename")).ToLocalChecked());
                                        ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:663:88: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
        if (filename->IsString() && isAppMetricsFile("index.js", toStdString(filename->ToString()))) {
                                                                                       ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:664:48: warning: 'ToObject' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
            Local<Value> grandparent = parent->ToObject()->Get(Nan::New<String>(asciiString("parent")).ToLocalChecked());
                                               ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:665:52: warning: 'ToObject' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
            Local<Value> gpfilename = grandparent->ToObject()->Get(Nan::New<String>(asciiString("filename")).ToLoca...
                                                   ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:666:99: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
            if (gpfilename->IsString() && isAppMetricsFile("launcher.js", toStdString(gpfilename->ToString()))) {
                                                                                                  ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
Release/obj.target/appmetrics/geni/appmetrics.cpp:684:89: warning: 'ToString' is deprecated: Use maybe version
      [-Wdeprecated-declarations]
            if (entry->IsString() && isAppMetricsFile("launcher.js", toStdString(entry->ToString()))) {
                                                                                        ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/suprith/.node-gyp/11.1.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
23 warnings and 2 errors generated.
make: *** [Release/obj.target/appmetrics/geni/appmetrics.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/suprith/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/suprith/.nvm/versions/node/v11.1.0/bin/node" "/Users/suprith/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@3.1.3 install: `node extract_all_binaries.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appmetrics@3.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suprith/.npm/_logs/2018-12-30T13_24_00_293Z-debug.log

Is there a workaround for this and I am also looking to install it in a alpine linux container in production. will this work.

**Comment by tobespc** [comment] 2019-01-09 15:01
Node 11 is currently unsupported in appmetrics

**Comment by carlonoelle** [comment] 2019-01-09 18:49
@tobespc Is this app still under active development? And will there be an update supporting this node version?

Thanks

**Comment by tobespc** [comment] 2019-01-10 09:17
This is still under development but typically, we only add support for the node releases that will go to LTS (so the even numbered ones), the interim development (odd number releases) we don't claim support for.  Thats not to say that we won't make it work, its just not something that is on our current release radart

**Comment by sumitsk20** [comment] 2019-04-20 14:26
does this module support node v10 ?

**Comment by nmargaritis** [comment] 2020-04-16 10:40
This module works only with node v10. **in current LTS v12 the module can not be installed due to node-gyp issues.** 

Note that v10 has a support up until April 2021. So currently the clock is ticking and I really do not know if you guys will consider using v10 instead of v12 for a performance evaluation module....  You already compromise performance by staying in v10.

**Comment by mattcolegate** [comment] 2020-04-28 23:50
Hi @nmargaritis, thanks for your comment - it's prompted me to update our automated testing for appmetrics-dash. You can see the PR I've raised for it (https://github.com/RuntimeTools/appmetrics-dash/pull/188) and hopefully you can see the resulting Travis run (https://travis-ci.org/github/RuntimeTools/appmetrics-dash/builds/680791283) that shows that on Linux and OSX appmetrics-dash works on all currently supported versions of Node.js (v10, v12, v13 and v14). For the Windows errors, we see the same kind of errors on appmetrics which is likely the cause - I've opened https://github.com/RuntimeTools/appmetrics/issues/637 to fix those up. In light of all appmetrics-dash installations with supported Node.js versions installing correctly (albeit with warnings) on OSX at this time, I'm going to close this issue.

**Closed by mattcolegate** 2020-04-28 23:50 UTC
