### ISSUE TITLE
Generate Node Report is broken

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics-dash#67] opened 2017-04-05 19:28 UTC
I've got a button that says, "Generate Node Report", but on click I'm told: 

node reporting not available

The dashboard should recognize this and disable the button (and also tell me how to enable it - I honestly have no idea what it is and why it isn't working).

**Comment by sam-github** [comment] 2017-04-05 20:32
duplicate of https://github.com/RuntimeTools/appmetrics-dash/issues/26 (and I agree the button should be disabled).

It means you don't have a compiler toolchain, btw, your `npm install` should have spewed some warnings to the effect that the optional node-report dependency failed to build.

**Closed by sam-github** 2017-04-05 20:32 UTC

**Comment by tobespc** [comment] 2017-04-06 07:39
@cfjedimaster we are working on improving the UX this should the feature be unavailable
